#! /usr/bin/env python
from helping_hand_nodes.database_tf_publisher import TfDatabasePublisher


if __name__ == "__main__":

    try:
        TfDatabasePublisher()
    except Exception as e:
	print("Exception occured when starting the node:\n{}".format(e))
