#! /usr/bin/env python
from helping_hand_services.configuration_capture import ConfigurationCapture


if __name__ == "__main__":
    
    try:
        ConfigurationCapture()
    except:
        pass

